# Configuration for production, only validate the database schema
spring:
  application:
    version: 1.0.0-prod

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false  # ← В продакшене лучше отключить
        format_sql: false

  # В PROD включаем Flyway для управления миграциями
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    # Уберите init-sqls - это не нужно